### ISSUE TITLE
Deprecated functionality: document_type

### ISSUE THREAD

**Issue by lachlansimpson** [guillaumeeb/pbs-elastic#1]
From version 7 of the ELK stack, `document_type` is [deprecated](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-document_type).

To create a similar result, there are a number of ways to do it, but one is:

In [filebeat-pbs-accounting.yml on line 34](https://github.com/guillaumeeb/pbs-elastic/blob/5d8750974f9aba5cf9719f11f049df690caa4580/accounting-logs/filebeat-pbs-accounting.yml#L34) replace

```
document_type: pbs_accounting
```

with

```
fields:
  pbs_accounting: true
fields_under_root: true
```

And then in [202-filter-pbssched.conf.j2 on line 2](https://github.com/guillaumeeb/pbs-elastic/blob/5d8750974f9aba5cf9719f11f049df690caa4580/accounting-logs/202-filter-pbssched.conf.j2#L2) replace
```
if [type] == "pbs_accounting" {
```

with
```
if [pbs_accounting] {
```

**Comment by guillaumeeb** [comment]
You are perfectly right, I did not update this repo... We are using 6.8 version in our setup, but the syntax we use now is:
```
  fields:
    source_type: pbs_accounting
```

And in logstash:
```
if [fields][source_type] == "pbs_accounting" {
```

But your solution looks a little more elegant.

**Comment by guillaumeeb** [comment]
Don't hesitate to propose a Pull Request for this change.

**Comment by lachlansimpson** [comment]
I've left that role now and am not in a position to test. I don't even have access to my code base. Sorry.
